learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', 'learning_logs')),
]

learning_logs/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #home page
    path('', views.index, name='index'),

    #List of TOPICS page.
    path('topics/', views.topics, name='topics'),
]

learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    """ Topic class is for Subjects"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic=models.ForeignKey('Topic', on_delete=models.PROTECT)
    text=models.TextField()
    date_added= models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
         if len(self.text) >= 50:
             return self.text[:50] + "..."
         else:
             return self.text

learning_logs/views.py
from django.shortcuts import render

# Create your views here.

from .models import Topic

def index(request):
    # Home Page
    return render(request, 'learning_logs/index.html')

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

learning_logs/templates/learning_logs/base.html
<!--this is the parent template for all the pages:-->
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <!--<style>-->
        <!--body{-->
        <!--background: #ffbc24;-->
        <!--}-->

    <!--</style>-->
</head>
<body>
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a>
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!--Home page for learning logs app-->
<!DOCTYPE html>
{% extends "learning_logs/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning_Logs</title>



</head>
<body>
{% block content %}
<h1 style="color: red;">Welcome Learning Logs Home page</h1>
<p>
    Learning Log helps you keep track of your learning, for any topic you're learning about.
</p>
{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
{% extends "learning_logs/base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LearningLogsTOPICS</title>
</head>
<body>
{% block content%}
<p>Topics</p>
<ul>
    {% for topic in topics%}
        <li>{{ topic }}</li>
    {% empty%}
        <li>No topics have been added yet.</li>
    {% endfor %}
</ul>

{%endblock content%}
</body>
</html>